### ISSUE TITLE
Default interpolation 

### ISSUE THREAD

**Issue by heebns** [ge-flight-analytics/ems-api-sdk#10]
Does anyone have background on how the default interpolation schemes are set on a parameter by parameter basis and/or who to contact about getting potential issues investigated? For at least 1x parameter I've been investigating recently appears to be set incorrectly (i.e. a bit packed word 	is set to linear)

**Comment by richardpineo** [comment]
Typically for issues about parameter configuration or the data behind the API, we will want to open a help desk ticket for our data engineers. 

To do this, you can email directly to:
@AVIATION ADI Support <aviationadisupport@ge.com>

In this case, I forwarded this question on to the help desk and asked them to reply to this thread so hopefully you will hear back within a week. Please let me know if the question is more urgent than than and I can help escalate or if you don't hear back within roughly that time frame.

-Richard

**Comment by richardpineo** [comment]
@heebns - I realize now that I should have gotten more information from you on this item since the data engineers who answer these types of questions have no way to get in contact with you. if you still have this question, would you email the support email listed above directly with your question and someone will get back to you. 
My apologies for the confusion.
