### ISSUE TITLE
API Proxies

### ISSUE THREAD

**Issue by BFNestico** [ge-flight-analytics/ems-api-sdk#8]
Currently I am using the following proxies with the Python EMS API....
'http':'http://%s:%s@PITC-Zscaler-Americas-Cincinnati3PR.proxy.corporate.ge.com:80' % 
'https':'https://%s:%s@PITC-Zscaler-Americas-Cincinnati3PR.proxy.corporate.ge.com:80' %

How do I know I am using the most efficient server for my location?  Is there a master list for all available servers and to identify user access?  

What is the difference between accessing "https://ceod.efoqa.com" vs "https://ems.efoqa.com" ?

Thanks,
Brian

**Comment by kylepope-ge** [comment]
If you're on the 3.x network, you can determine which proxy is best by downloading your "pac" file by visiting the following link in your web browser: http://corp.setpac.ge.com/pac.pac. If you open up the file in a text editor, you should see a "Main_Proxy" assignment on line 9 -- this is probably the best one to use.

Regarding the difference between the ceod vs ems servers -- the ceod server has been set up specifically for engines usage and is configured with more resources and a load balancer to be able to handle heavier load. The ems server is the standard server we use with the rest of our customers and it doesn't have these added capabilities. From your perspective, using one over the other shouldn't be different since the Python wrapper abstracts this away for you. Under the covers, the only difference you might see is that the URLs that your python script will use might be slightly different... Many of our URLs have an "emsSystemId" integer and this might be different for each of those servers. For example, the value might be different when a request is made to the following URL: https://server/api/v2/ems-systems/{emsSystemId}/analytics/query
